[tool.poetry]
name = "ml1adv-cirrhosis"
version = "0.1.0"
description = "Cirrhosis survival classification homework with CatBoost and Optuna."
authors = ["Ksenia Zakharova <ksenia@example.com>"]
readme = "README.md"
packages = [{ include = "ml1adv_cirrhosis" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
pandas = "^2.3.0"
numpy = "^2.3.0"
scikit-learn = "^1.7.0"
catboost = "^1.2.8"
optuna = "^4.4.0"
jupyter = "^1.1.1"
nbformat = "^5.10.4"
joblib = "^1.5.1"
clearml = "^2.0.2"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
